/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = 'avdjlznhehigqgmeubpb'
export const publicAnonKey =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF2ZGpsem5oZWhpZ3FnbWV1YnBiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk0MTk5OTQsImV4cCI6MjA4NDk5NTk5NH0.8HG1GMYIME6cGbdMMGl74Zmooib06JBsWw3Ek1Ldxkc'
